;; auto-comleteの設定
(when (require 'auto-complete-config nil t)
  (ac-config-default)
  (add-to-list 'ac-dictionary-directories "~/.emacs.d/elisp/ac-dict")
  (add-to-list 'ac-modes 'text-mode)
  (add-to-list 'ac-modes 'fundamental-mode)
  (add-to-list 'ac-modes 'org-mode)
  (add-to-list 'ac-modes 'yatex-mode)
  (ac-set-trigger-key "TAB")
  (setq ac-use-menu-map t)
  (setq ac-use-fuzzy t)
  ;;(define-key ac-mode-map (kbd "M-TAB") 'auto-complete)
  )
